### ISSUE TITLE
리팩토링 및 통합테스트 추가

### ISSUE THREAD

**Issue by kimihiqq** [kimihiqq/Kotlin-gRPC-Server#15]
### 💻 Describe
이번 이슈에서는 JPA 적용에 따른 테스트 컨테이너 환경 설정 파일을 재구성하고, 통합테스트를 진행합니다. 그리고 서비스 로직 내 예외처리와 같은 부분들을 포함한 리팩토링을 진행합니다. 

### ✅ Tasks

- [x] 테스트 컨테이너 환경 설정 파일 재구성
- [x] 통합 테스트 구현
- [x] 서비스 코드 내 예외처리 로직 리팩토링
