### ISSUE TITLE
Infrastructure Layer 개발

### ISSUE THREAD

**Issue by kimihiqq** [kimihiqq/Kotlin-gRPC-Server#5]
### 💻 Describe
이번 이슈에서는 데이터베이스 연결 설정, Key-Value 데이터 처리를 위한 리포지토리 구현, 그리고 관련 단위 및 통합 테스트를 구현합니다.

### ✅ Tasks
- [ ]  infrastructure 모듈을 boot 및 provider 서브모듈로 분리하여 데이터베이스 연결 및 기술적 세부사항 관리.
- [ ]  Docker 설정 및 데이터베이스 초기화
- [ ]  DataSource 설정 및 관리
- [ ] 단위 및 통합 테스트 구현

### 🙋🏻 More
데이터베이스 초기화 및 관리는 Docker와 Flyway를 사용할 계획입니다.
